language: ruby
rvm:
- 2.1
before_script:
- chmod +x ./script/deploy-gh
script: "./script/deploy-gh"
branches:
  only:
  - master

cache:
  bundler: true
  directories:
    - $HOME/.rvm

env:
  global:
  - GH_USERNAME=mayarichman
  - GH_OWNER=the-engine-room
  - GH_REPO=responsible-data-handbook
  - GH_REF=github.com/the-engine-room/responsible-data-handbook.git
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: jCjzDb8EPzXfE3FDNKyipCmBMjttyn4MM0Q+EB2cWBSmuqyNuoBmP1IZpFgkq+NqonMzhVBZOhwpdNz3mIA+/FAlj337FvZn6+mwDl/wfDBq9ioJ9S7UvpnXgInzwgHxBDeOSaatTskvENuxkNNIaTXHKqHzSfkPcaEtB4RO3CjVdmjhjHIEjqZfUe7E/loyvfXkvEZTZ+yC3SOl38CD/0NtxeCBiJkFRzOKfJMVnqmU0R9zC/hxMvPytdKqKoRLJOQyNOUauv8aienAKxeIpPvlF2vc+Hv/YN/kLEp2fbvTBhNRICZVwFsEXTyU8Vz7cL1v8/UsVy7UvQIJBJ97eg3vQYbO0KOvogC2EMh5vuWW0k5E5s1NfflphmL8MR7zTQJdueadyhAxCA+eTaNSO4Iy0/h2mytPDSZo5EvtvIAJ0ejFBpX3ttX/LKINDWED5OYXKK3wSA2AN6X3bZBEfCNr7uyhF8oWw26nGpEgLuyfys9fI5WWMhLbFW7T7lYxlrQbztzsdZku6izKvtThPwF5rsbXg4BTxWn6AeExsX7WlQ6h46/jDlv1LmNm64IABK/qwWThOdDHgbylJSLArP9Z1yZDIKnRFGTGlGvqn6w5vMYZROGKMC2I1Q1AJWGMMiWiKU7hhPBkDp8jKJAVy+hgTigQZc9RabxhWPwXxZs=
sudo: false
