language: ruby
rvm:
- 2.1
before_script:
- chmod +x ./script/deploy-gh
script: ./script/deploy-gh
branches:
  only:
  - master
cache:
  bundler: true
  directories:
  - $HOME/.rvm
env:
  global:
  - GH_USERNAME=theengineroom-engineers
  - GH_OWNER=the-engine-room
  - GH_REPO=responsible-data-handbook
  - GH_REF=github.com/the-engine-room/responsible-data-handbook.git
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: eu4Rzgo73rgkFdSyF09xNU0/r3tKkNIBgLlGIofQ3Dp4azQJThaQB90XR6ZCUAod5kyEF422g4Rb+a24djQ0P+34xuwMzU34AtV8NLWR664OSJdAYbPbIMYyn4cW5eq3w64RuE7lm2H3oig830mFRgOvtVH1rKLKzj8R6sLAgTlrelUjBpnc2Fp1iYzvuZZao0uLvRZjrb36j0NzvUlTisVbqI+C2gyrDwJqWCuDnkWcjelFvueQOGg+Du/0bzUleOlr2KeVO67PZjC4mGCg3oWNCoR9HRlmYZEXHB/CVo5rIqoiAlAFU0VAu7bb07SvaD8zaX7KLf1H6aITKHzvCEMjdug3yiHumVG4LPhCecsbFPc1f9BaJ/00YD9rQRsGF2t6rEDSgvkrRRTCqjN2JGsFmGMacnh50NgQYwWgTtusCE02FiRs3zf2UgZNE5ME2xdE34K04tXMDjd/dAF1/lABtkjodMYEarcovtf448GksVIOxzipEtCn87yHVVUMz42SSOWApTfAFDGSx78tGRIhuXNVu11gqyiIrPDgS/AopT6nYq05qYK8UmcZ0+qh1Tc/9e0b2RQIUemVcZ2a2/PCWk16iT81h2VB1ZjpbAKP0j2W9aEgQYKJLs+wpyNcjqFrn+11Wgf1gLnhgoxOBq2m0I6k1dk8Qiv8yWurW50=
sudo: false
