# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Responsible Data Handbook 
email: contact@responsibledata.io
description: A primer on why Responsible Data is a relevant concern for international development work. 


baseurl: "/responsible-data-handbook" # the subpath of your site, e.g. /blog
url: "http://the-engine-room.github.io" # the base hostname & protocol for your site

twitter_username: engnroom
github_username:  the-engine-room

# Build settings
markdown: kramdown
kramdown: 
  parse_block_html: true

#Permalink dictates url slugs, changing styles of slugs in _posts folder to not use "date" constructoin
permalink: /:categories/:title.html


#exclude from _site dir created by `jekyll build`
exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock